spring.application.name=crms
# MongoDB Connection String
# Format: mongodb://<host>:<port>/<database_name>
spring.data.mongodb.uri=mongodb://localhost:27017/CRMS
spring.data.mongodb.database=CRMS
spring.mongodb.uri=mongodb://localhost:27017/CRMS
spring.mongodb.database=CRMS

# Server Port (Optional, helps avoid conflicts)
server.port=8080

