export const projects = [
  {
    id: "001A",
    name: "Project Alpha",
    description: "First project",
    status: "ACTIVE",
    clientName: "ABC Company",
    budget: 15000,
    progress: 70,
    lastUpdated: "2026-04-26",
  },
  {
    id: "002B",
    name: "Project Beta",
    description: "Second project",
    status: "ACTIVE",
    clientName: "XYZ Ltd",
    budget: 22000,
    progress: 45,
    lastUpdated: "2026-04-22",
  },
  {
    id: "003C",
    name: "Project Gamma",
    description: "Third project",
    status: "PLANNING",
    clientName: "Global Tech",
    budget: 10000,
    progress: 10,
    lastUpdated: "2026-04-20",
  },
];